# Generated by Django 3.2 on 2022-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='animes',
            field=models.ManyToManyField(related_name='listas', to='animes.Anime'),
        ),
    ]
